// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion


/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Bookhead Documentation',
  tagline: 'Documentation for syncing your bookstore inventory online',
  favicon: 'img/bookhead-single.png',

  // Set the production url of your site here
  url: 'https://docs.bookhead.net',

  baseUrl: '/',

  // GitHub pages deployment config
  organizationName: 'book-head',
  projectName: 'documentation',
  trailingSlash: false,

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  // Even if you don't use internalization, you can use this field to set useful
  // metadata like html lang. For example, if your site is Chinese, you may want
  // to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl:
            'https://github.com/book-head/documentation/tree/main/',
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  // Each sales channel + standalone tool is its own isolated docs instance:
  // its own folder, URL base, and autogenerated sidebar. This keeps every
  // section self-contained — no section's sidebar can show another's pages.
  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'shopify',
        path: 'shopify',
        routeBasePath: 'shopify',
        sidebarPath: require.resolve('./sidebars-shopify.js'),
        editUrl: 'https://github.com/book-head/documentation/tree/main/',
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'squarespace',
        path: 'squarespace',
        routeBasePath: 'squarespace',
        sidebarPath: require.resolve('./sidebars-squarespace.js'),
        editUrl: 'https://github.com/book-head/documentation/tree/main/',
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'ebay',
        path: 'ebay',
        routeBasePath: 'ebay',
        sidebarPath: require.resolve('./sidebars-ebay.js'),
        editUrl: 'https://github.com/book-head/documentation/tree/main/',
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'biblio',
        path: 'biblio',
        routeBasePath: 'biblio',
        sidebarPath: require.resolve('./sidebars-biblio.js'),
        editUrl: 'https://github.com/book-head/documentation/tree/main/',
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'alibris',
        path: 'alibris',
        routeBasePath: 'alibris',
        sidebarPath: require.resolve('./sidebars-alibris.js'),
        editUrl: 'https://github.com/book-head/documentation/tree/main/',
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'canva',
        path: 'canva',
        routeBasePath: 'canva',
        sidebarPath: require.resolve('./sidebars-canva.js'),
        editUrl: 'https://github.com/book-head/documentation/tree/main/',
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'sheets',
        path: 'sheets',
        routeBasePath: 'sheets',
        sidebarPath: require.resolve('./sidebars-sheets.js'),
        editUrl: 'https://github.com/book-head/documentation/tree/main/',
      },
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Replace with your project's social card
      image: 'img/bookhead-dots.png',
      navbar: {
        logo: {
          alt: 'Bookhead Logo',
          src: 'img/bookhead-horizontal.png',
        },
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'tutorialSidebar',
            position: 'left',
            label: 'Documentation',
          },
          // "Selling on channels" makes each channel section directly reachable
          // from the navbar. It is AUTO-HIDDEN on /shopify pages by the custom
          // NavbarItem wrapper (src/theme/NavbarItem) so the Shopify section
          // never shows another channel's name to a visitor or App Store
          // reviewer. Do not rename the label without updating that wrapper.
          {
            type: 'dropdown',
            label: 'Selling on channels',
            position: 'left',
            items: [
              {label: 'Shopify', to: '/shopify'},
              {label: 'Squarespace', to: '/squarespace'},
              {label: 'eBay', to: '/ebay'},
              {label: 'Biblio', to: '/biblio'},
              {label: 'Alibris', to: '/alibris'},
            ],
          },
          // "Apps" groups the standalone creative tools (not sales channels),
          // so naming them here is safe on every page, including /shopify.
          // Sales channels are intentionally NOT listed in the navbar — they're
          // reached from the "Selling on channels" index inside Documentation —
          // so no other channel is ever named in the Shopify section's chrome.
          {
            type: 'dropdown',
            label: 'Apps',
            position: 'left',
            items: [
              {label: 'Bookhead for Canva', to: '/canva'},
              {label: 'ISBN Magic for Google Sheets', to: '/sheets'},
            ],
          },
          // Roadmap + Changelog (Canny) and the main site. Generic labels with
          // no channel names, so they're safe on every page including /shopify.
          {
            href: 'https://bookhead.canny.io',
            label: 'Roadmap',
            position: 'right',
          },
          {
            href: 'https://bookhead.canny.io/changelog',
            label: 'Changelog',
            position: 'right',
          },
          {
            href: 'https://bookhead.net',
            label: 'Bookhead site',
            position: 'right',
          },
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Documentation',
            items: [
              {
                label: 'Overview',
                to: '/docs/intro',
              },
              {
                label: 'Integrations',
                to: '/docs/integrations',
              },
              {
                label: 'Managing inventory',
                to: '/docs/inventory',
              },
              {
                label: 'Selling on channels',
                to: '/docs/sales-channels',
              },
            ],
          },
          {
            title: 'Features',
            items: [
              {
                label: 'Collections & staff picks',
                to: '/docs/collections',
              },
              {
                label: 'FTP integration',
                to: '/docs/ftp-integration',
              },
            ],
          },
          {
            title: 'Help',
            items: [
              {
                label: 'Contact support',
                href: 'mailto:support@bookhead.net',
              },
              {
                label: 'Roadmap',
                href: 'https://bookhead.canny.io',
              },
              {
                label: 'Changelog',
                href: 'https://bookhead.canny.io/changelog',
              },
              {
                label: 'Bookhead',
                href: 'https://bookhead.net'
              }
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Bookhead.`,
      },
      // prism: {
      //   theme: lightCodeTheme,
      //   darkTheme: darkCodeTheme,
      // },
    }),
};

module.exports = config;
